### ISSUE TITLE
fail at build

### ISSUE THREAD

**Issue by lhcpig** [appunite/docker#28]
It return `bash: gradlew: command not found` after I run  `docker run --tty --interactive --volume=$(pwd):/opt/workspace --workdir=/opt/workspace --rm jacekmarchwicki/android:java7  /bin/sh -c "./gradlew build"`

**Comment by jacek-marchwicki** [comment]
This means that `./gradlew` is not on your current path. Probably current path is your project or you dodn't have installed gradle wrapper, look: https://docs.gradle.org/current/userguide/gradle_wrapper.html
