### ISSUE TITLE
Java8 Unknown tag

### ISSUE THREAD

**Issue by richersoon** [appunite/docker#32]
When I execute 
`docker run --tty --interactive --volume=$(pwd):/opt/workspace --workdir=/opt/workspace --rm jacekmarchwicki/android:java8  /bin/sh -c "./gradlew build"`

I got unknown tag.

**Comment by jacek-marchwicki** [comment]
@richersoon this docker is new and it has bug with installing android sdk - we are working on this.

sorry

**Comment by jacek-marchwicki** [comment]
You should have now tags: `jacekmarchwicki/android:java8-r24-4-1` and `jacekmarchwicki/android:java8-r24-3-3` sorry for delay
