### ISSUE TITLE
Failed to find android-23

### ISSUE THREAD

**Issue by JemarJones** [appunite/docker#37]
Attempting to use this docker image to build an android app i get the following issue failing my builds:

    failed to find target with hash string 'android-23' in: /opt/android-sdk-linux

Looking at docker hub i can see another user has the same issue. Any help?

**Comment by jacek-marchwicki** [comment]
What exactly version you are using? 

android-23 is installed only on tags:
- `java7-r24-4-1`
- `java8-r24-4-1`
- `java8-r24-3-3`
- `java8-r25`

**Comment by JemarJones** [comment]
Oh, yes you are right. I realized after i made this issue that there were different tags. Thanks!
