### ISSUE TITLE
Setting wrong default version of JAVA

### ISSUE THREAD

**Issue by bhavinmdesai** [appunite/docker#45]
I used `jacekmarchwicki/android:java7-8` image and when my EC2 instance is running I am executing `java -version` command. It prints following:

`$ java -version`
`java version "1.7.0_121"`
`OpenJDK Runtime Environment (amzn-2.6.8.1.69.amzn1-x86_64 u121-b00)`
`OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)`

Don't you think it should print OracleJDK ?

PS: Can it be the reason, I am executing 
`$ java -version` from another user ?

**Comment by jacek-marchwicki** [comment]
@bhavinmdesai you probably executed `java -version` on your Amazon EC2 shell outside docker. This seam reasonable because version of your jdk is **amzn**-2.6.8.1.69.amzn1-x86_64 u121-b00.

try to execute:
```bash
docker run --tty --interactive jacekmarchwicki/android:java7-8 java -version
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

or run `/bin/bash` inside docker then `java -version` in that bach: 

```bash
docker run --tty --interactive jacekmarchwicki/android:java7-8 /bin/bash
java -version
> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
