### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by pragnesh-is** [appunite/docker#46]
Most of times i am getting this error. I am using docker for mac.

**Comment by jacek-marchwicki** [comment]
I think this is related to network issues. When do you have such problems? During downloading sdk/tools/dependencies?

**Comment by pragnesh-is** [comment]
Just after running command: Here is output, But at same time, if i am running command without docker than this error never occurs, so i was thinking if anything required in image.

Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip

Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

**Comment by jacek-marchwicki** [comment]
Maybe you have some SSL proxy? Docker image has separate certificates set. Or you have some problems with network in docker.

Maybe try to run bash inside this docker and then use wget to download this file or others. You can temporary change URL in gradle-wrapper.properties to one with http instead of https

**Comment by pragnesh-is** [comment]
as workaround mounted a .gradle directorty so everytime it is not going to download everything.

**Comment by jacek-marchwicki** [comment]
you can also set:

```bash
export ANDROID_HOME=$(pwd)/.android
mkdir -p "${ANDROID_HOME}/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "${ANDROID_HOME}/licenses/intel-android-extra-license"
```

and link .android directory so you will not download sdk from scratch
