### ISSUE TITLE
Cannot decide host bitness because $SHELL is not properly defined

### ISSUE THREAD

**Issue by Dima564** [appunite/docker#54]
When I'm trying to run an emulator with 
` emulator -avd test -no-audio -no-window -gpu off -wipe-data &`

I'm getting the following error: 
` WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.

       Either one will allow you to use the 32-bit binaries, but please be
       aware that these will disappear in a future Android SDK release.
       Consider moving to a 64-bit Linux system before that happens.`

**Comment by Dima564** [comment]
Running ` SHELL=/bin/bash emulator -avd test -no-audio -no-window -gpu off -wipe-data &` also fails. Logs:

```emulator: WARNING: Classic qemu does not support SMP. The hw.cpu.ncore option from your config file is ignored.
Creating filesystem with parameters:
    Size: 69206016
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 4224
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 16896
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/4224 inodes and 1302/16896 blocks
qemu: could not open disk image /root/.android/avd/test.avd/sdcard.img: Interrupted system call```

**Comment by jacek-marchwicki** [comment]
Actually we don't use emulator inside dockers because software emulators are too slow and using kvm requires sharing base machine resources that is not enough secure.
I wonder if its even possible to use software emulation with newer android versions.

To use kvm I think you need to compile kvm, add `--privilaged` and share `/dev/kvm` directory from your host. But I didn't tested this solution since a year

**Comment by Dima564** [comment]
Got it, thanks for the info. 
So, you just run unit tests inside docker and instrumental tests on physical slave machines?

**Comment by jacek-marchwicki** [comment]
@Dima564 you can use [Firebase Test Lab](https://firebase.google.com/docs/test-lab/) I think its 5$/h
