### ISSUE TITLE
Building project with Google-repository

### ISSUE THREAD

**Issue by lewinskimaciej** [appunite/docker#55]
I'm using [java7-8](https://github.com/appunite/docker/tree/master/java7-8) image and according to the instructions.

I'm having hell of a problem building an apk that uses firebase messaging.
It has everything that [official guide](https://firebase.google.com/docs/android/setup) mentions(i.e. dependency for google-services 3.0.0, compile 'com.google.firebase:firebase-messaging:10.2.4' and apply plugin at the end of app build.gradle. It works perfectly fine while building outside of docker yet inside, it results in:
```
(...)
Execution failed for task ':app:resolveDebugDependencies'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:10.2.4.
     Searched in the following locations:
     (...)
 > Could not find com.google.firebase:firebase-messaging:10.2.4.
     Searched in the following locations:
     (...)
```
I'm guessing it lacks Google repository or something. Any idea how I can make it work?

**Comment by lewinskimaciej** [comment]
I guess downloading sdk and doing android update works for now. I don't honestly know why this would work automatically.

**Comment by tallnato** [comment]
@lewinskimaciej have you found any solution without having to download the SDK?

**Comment by jacek-marchwicki** [comment]
Try to add: `compile "com.google.android.gms:play-services-base:<your-version-of-firebase>"`.

There is an issue in android gradle plugin that does not detect `com.google.firebase:*` dependencies but it detect  `com.google.android.gms:*` so it will also install firebase all together
