### ISSUE TITLE
 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by si-huynh** [appunite/docker#56]
I used your image for Bitbucket pipeline - My project is using Java7

Ouput:
* What went wrong:
A problem occurred evaluating project ':api'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

Update:

I used image jacekmarchwicki/android:java7-8

Output:
* What went wrong:
A problem occurred configuring project ':api'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

**Comment by jacek-marchwicki** [comment]
On those images there is no Android SDK because newer gradle plugins can download sdk. 
You probably need to upgrade your android plugin to: `classpath 'com.android.tools.build:gradle:2.3.2'`

**Comment by si-huynh** [comment]
I upgraded android plugin build:gradle:2.3.2 but issue not resolved.

**Comment by jacek-marchwicki** [comment]
Did you use comand as descrbed in: https://github.com/appunite/docker/blob/master/ubuntu-16-04-java7-8/README.md

```
export GRADLE_USER_HOME="$(pwd)/.gradle"
export ANDROID_HOME="$(pwd)/.android"
mkdir -p "${ANDROID_HOME}/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "${ANDROID_HOME}/licenses/intel-android-extra-license"
./gradlew --parallel --stacktrace --no-daemon build 
```
