### ISSUE TITLE
java7-8 does not contain android SDK

### ISSUE THREAD

**Issue by henning** [appunite/docker#57]
The Readme of the java8-r25 image Dockerfile says "deprecated"  and tells me to use the java7-8 image. But that one does not contain android SDK, even so the README suggests it does.

But it actually can't, the Android SDL installation routine that I see in the java8-r25 Dockerfile is missing.

So, I'm confused which image is supposed to be used.

**Comment by jacek-marchwicki** [comment]
The newest version is https://github.com/appunite/docker/blob/master/ubuntu-16-04-java7-8/README.md - we use it for our Android builds. Newest versions of Android plugin should download ask automatically so ask is not included. You can cache SDK for subsequent builds

**Comment by henning** [comment]
I'm sorry but I don't understand the explanation on where the android sdk should come from.
There is supposed to be something with an automated download when needed?

It does not work for me. 
I try to use it to build and ionic framework project. That worked fine with the java8-r25 image, but fails with java7-8 and ubuntu-16-04-java7-8.

I only get 

"Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory."

And also searching the full container does not show me any sign that there is an android SDK installed in some way anywhere.

**Comment by henning** [comment]
Wait - if I set the variables properly as explained in the readme, the android SDK seems tio get installed. 

But then I still get "Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK."

**Comment by jacek-marchwicki** [comment]
I never heard abut problem: `Error: Could not find gradle wrapper within Android SDK`.
This issue is quite wired because when you build you execute `./gradlew` is gradle wrapper and it is (or should be) located in your project.

I saw some references to your error on google when building cordova and ionic are you are using them?

**Comment by henning** [comment]
Yes, I use ionic ( mentioned it above) - I also found some posts, but not yet a solution.
I posted here because I hoped to get an idea what I might be doing wrong.

The thing is, with your old image, it worked well, with the latest not anymore.

I will notify you here when I finally found it out - it's a legacy project and I'm not working on it every day, so it can take a while.

**Comment by jacek-marchwicki** [comment]
So probably you need to install sdk manually. Probably you can use something like this:

```bash
(cd /opt && wget --output-document=android-sdk.tgz --quiet https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz && \
  tar xzf android-sdk.tgz && \
  rm -f android-sdk.tgz && \
  chown -R root.root android-sdk-linux && \
  /opt/tools/android-accept-licenses.sh "android-sdk-linux/tools/android update sdk --all --no-ui --filter platform-tools,tools" && \
  /opt/tools/android-accept-licenses.sh "android-sdk-linux/tools/android update sdk --all --no-ui --filter platform-tools,tools,build-tools-22.0.1,build-tools-23.0.3,build-tools-24.0.3,build-tools-25.0.0,build-tools-25.0.1,android-21,android-22,android-23,android-24,android-25,addon-google_apis_x86-google-21,extra-android-support,extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services,sys-img-armeabi-v7a-android-24")
```
