### ISSUE TITLE
confd 0.12.0 cannot connect to etcd endpoint without specifying scheme

### ISSUE THREAD

**Issue by fk1blow** [appunite/docker#58]
Have updated the confd version you wget inside the Dockerfile, and using confd 0.12.0-alpha-3, the endpoint to etcd backend should have the scheme, otherwise confd won't be able to connect to etcd cluster(so instead of `confd -node 10.0.0.1` try `confd -node http://10.0.0.1`).
Not really an issue per se, but have discovered it while playing with this setup!

**Comment by jacek-marchwicki** [comment]
are you referring to nginx-confd sub-project?  Actually we don't use this configuration anymore. Its deprecated

**Comment by fk1blow** [comment]
ok, have you open sourced the new configuration? Just curious

**Comment by jacek-marchwicki** [comment]
Actually we don't use nginx with confd anymore - so there is nothing to open source :/

**Comment by fk1blow** [comment]
ok, thanks for your reply!
