### ISSUE TITLE
Warning: License for package Android SDK Build-Tools (any version) not accepted

### ISSUE THREAD

**Issue by benliger** [appunite/docker#60]
Hello, 

Gitlab failed to compile since today:

> Checking the license for package Android SDK Build-Tools 26.0.1 in /sdk/licenses
> Warning: License for package Android SDK Build-Tools 26.0.1 not accepted.

Do you have any idea what changed regarding licenses ?

Thanks

**Comment by jacek-marchwicki** [comment]
Actually nothing has changed but in build-tools<`26.0.1` Google introduced new license for theirs SDK. 

If you are accepting theirs new license you need to accept all licenses:

```bash
mkdir -p "${ANDROID_HOME}/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "${ANDROID_HOME}/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "${ANDROID_HOME}/licenses/intel-android-extra-license"
```

In previous example we had:

```bash
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
```

so you need to switch to:

```bash
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "${ANDROID_HOME}/licenses/android-sdk-license"
```

I'll add this to repository documentation

**Comment by benliger** [comment]
thanks a lot!
